steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: dependency
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo //registry.npmjs.org/:_authToken=$$NPM_TOKEN > .npmrc
        npm ci
    secretEnv: ['NPM_TOKEN']

  - name: 'gcr.io/cloud-builders/npm'
    id: test
    args: ['test']

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/publish_token
    secretEnv:
      NPM_TOKEN: CiQA4RDOWdrx+r3ZCMMAYU+kI/+5cDjDG8W1FVmwUe7lA/hCxSkSTQCM5sIB04ZbQUH3FhF1wC9boXezWZCk3x5YEf3IyXZmOuHbMc+mFf6K1RXZH7HsZTpeb/Go9NVVHpfNplcbxiygv8b2Ewa11h1wkbqZ
