steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${TAG_NAME}" =~ ^release-canary$ ]]; then
          echo //registry.npmjs.org/:_authToken=$$NPM_TOKEN > .npmrc
          npm version 0.0.0-${SHORT_SHA} --git-tag-version=false
          npm publish
          npm dist-tag add @titicaca/eslint-config-triple@0.0.0-${SHORT_SHA} canary
        fi
    secretEnv: ['NPM_TOKEN']

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/publish_token
    secretEnv:
      NPM_TOKEN: CiQA4RDOWdrx+r3ZCMMAYU+kI/+5cDjDG8W1FVmwUe7lA/hCxSkSTQCM5sIB04ZbQUH3FhF1wC9boXezWZCk3x5YEf3IyXZmOuHbMc+mFf6K1RXZH7HsZTpeb/Go9NVVHpfNplcbxiygv8b2Ewa11h1wkbqZ
