steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: dependency
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo //registry.npmjs.org/:_authToken=$$NPM_TOKEN > .npmrc
        npm ci
    secretEnv: ['NPM_TOKEN']

  - name: 'gcr.io/cloud-builders/npm'
    id: test
    args: ['test']

  - name: 'gcr.io/cloud-builders/npm'
    id: publish
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${TAG_NAME}" =~ ^release-canary$ ]]; then
          PACKAGE_NAME=@titicaca/eslint-config-triple
          CANARY_VERSION=0.0.0-${SHORT_SHA}
          npm version $$CANARY_VERSION --git-tag-version=false
          npm publish --tag canary
        fi

substitutions:
  _SLACK_NOTIFY_CHANNEL: '#triple-web-dev'
  _SVC_BASENAME: 'eslint-config-triple'
  _AUTO_TAGGING_ENABLED: 'false'

secrets:
  - kmsKeyName: projects/titicaca-ci/locations/global/keyRings/npm/cryptoKeys/publish_token
    secretEnv:
      NPM_TOKEN: CiQA4RDOWdrx+r3ZCMMAYU+kI/+5cDjDG8W1FVmwUe7lA/hCxSkSTQCM5sIB04ZbQUH3FhF1wC9boXezWZCk3x5YEf3IyXZmOuHbMc+mFf6K1RXZH7HsZTpeb/Go9NVVHpfNplcbxiygv8b2Ewa11h1wkbqZ
