name: canary-on-review

on:
  pull_request_review:
    types: [submitted]

jobs:
  canary:
    if: github.event.review.state == 'commented' && contains(github.event.review.body, 'canary publish')
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [12.x]

    env:
      SLACK_CHANNEL: "#triple-web-dev-notifications"
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: "ESLint Config Triple"
      SLACK_ICON_EMOJI: ":eslint:"
      SLACK_COLOR: gray
      SLACK_FOOTER: "Triple Frontend"
      SLACK_AUTHOR_NAME: ${{ github.event.sender.login }}
      SLACK_AUTHOR_ICON: "${{ github.event.sender.avatar_url }}"
      SLACK_GITHUB_EVENT_NAME: "${{ github.event_name }}"
      SLACK_GITHUB_REPOSITORY: "${{ github.repository }}"
      SLACK_DETAIL_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Recognize head sha of pull request
        run: |
          PR_SHA=${{ github.event.pull_request.head.sha }}
          PR_REF=${{ github.event.pull_request.head.ref }}
          echo ::set-env name=PR_NUMBER::${{ github.event.pull_request.number }}
          echo ::set-env name=PR_SHA::$PR_SHA
          echo ::set-env name=PR_REF::$PR_REF
          echo ::set-env name=SLACK_GITHUB_REF::$PR_REF
          echo ::set-env name=PR_SHORT_SHA::${PR_SHA:0:7}
          echo ::set-env name=PR_TITLE::${{ github.event.pull_request.title }}
          echo ::set-env name=SLACK_TOPIC::${{ github.event.pull_request.title }}

      - name: Reaction
        run: |
          curl -v \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/comments \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -f --request POST \
            -d "{\"body\":\"@${{ github.event.sender.login}} I got it! :rocket: \"}"

      - name: Git checkout@v2
        uses: actions/checkout@v2

      - name: Define canary version
        run: |
          echo ::set-env name=CANARY_VERSION::v$(cat package.json | jq -r '.version')-${{ env.PR_SHORT_SHA }}

      - name: Notify build start to slack
        env:
          SLACK_TITLE: ":rocket: Build Started"
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify

      - name: Cache .npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Build
        run: |
          npm ci
          npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Notify build and test success to slack
        if: success()
        env:
          SLACK_TITLE: ":tada: Build Succeed"
          SLACK_COLOR: success
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify

      - name: Notify build and test fail to slack
        if: failure()
        env:
          SLACK_TITLE: ":x: Build Failed"
          SLACK_COLOR: success
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify

      - name: Notify deploy start to slack
        env:
          SLACK_TITLE: ":rocket: Deploy Started"
          SLACK_TOPIC: "Publishing `${{ env.CANARY_VERSION}}`"
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify

      - name: Tag canary version and publish to npm
        run: |
          npm version ${{ env.CANARY_VERSION }} --git-tag-version=false
          npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Notify deploy success to slack
        if: success()
        env:
          SLACK_TITLE: ":tada: Publish Succeed"
          SLACK_COLOR: success
          SLACK_TOPIC: "`${{ env.CANARY_VERSION}}`"
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify

      - name: Notify deploy fail to slack
        if: failure()
        env:
          SLACK_TITLE: ":x: Publish Failed"
          SLACK_COLOR: fail
          SLACK_TOPIC: "`${{ env.CANARY_VERSION}}`"
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx @titicaca/gha-tools notify
