name: CD

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'release-prod-*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix: 
          node-version: [12.x]
    steps:
      - name: Git checkout@v2
        uses: actions/checkout@v2

      - name: Notify build start to slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: good
          SLACK_TITLE: Build WORKING

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache .npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Build
        run: |
          npm ci
          npm test
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Notify build and test success to slack
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: good
          SLACK_TITLE: ${{ ':tada:' }} Build SUCCESS

      - name: Notify build and test fail to slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: warning
          SLACK_TITLE: ${{ ':x:' }} Build FAIL

      - name: Notify deploy start to slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: good
          SLACK_TITLE: Deploy WORKING

      - name: Publish to npm
        run: |
          npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Notify deploy success to slack
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: good
          SLACK_TITLE: ${{ ':tada:' }} Deploy SUCCESS
  
      - name: Notify deploy fail to slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: CMSJHHMA4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GHA Notifications
          SLACK_ICON_EMOJI: ':gear:'
          SLACK_COLOR: warning
          SLACK_TITLE: ${{ ':x:' }} Deploy FAIL