name: CI
on:
  push:
    branches:
      - '**'

env:
  # Node.js
  NODE_VERSION: '20'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm run lint

      - run: pnpm run test
